<?php

namespace Armor\Handle;

use Exception;

/**
 * The route object generated by the `Router` class and used by it. This 
 * is where the path regexes, the parsers and the callback of each path
 * are stored.
 * 
 *  
 * @see \Armor\Handle\Router
 */
class Route {
    /**
     * The regex that provides information about if the path requested corresponds to this route.
     * @var \string
     */
    private $pattern;
    /**
     * The callback that will be used to handle the request.
     * 
     * @var \callable
     */
    private $callback;
    /**
     * The route parameters definitions.
     * 
     * @var \array
     */
    private $parameters;
    /**
     * The parsers of each route parameter, if any.
     * 
     * @var \array
     */
    private $parsers;
    /**
     * The custom parser defined by the framework user. It's should usually be set via `Route#_addParser`,
     * which is accessible via `RouteInterface#setParser`.
     * 
     * @var \callable
     */
    private $customParser;

    /**
     * @param \string $routePattern The regex that provides information about 
     * if the path requested corresponds to this route.
     * @param \array $routeParameters The route parameters definitions.
     * @param \callable $routeCallback The callback that will be used to handle the request.
     * @param \array $parsers The parsers of each route parameter, if any.
     */
    public function __construct(
        string $routePattern,
        array $routeParameters,
        callable $routeCallback,
        array $parsers=array()
    ) {
        $this->pattern = $routePattern;
        $this->callback = $routeCallback;
        $this->parameters = $routeParameters;
        $this->parsers = $parsers;
    }

    /**
     * Returns if the path requested (`$pathto`) can be handled by this route object.
     * And at the same time, only if the path matches, parses the path to get the 
     * "route/path parameters" specified previously.
     * 
     * @param \string $pathto The path requested by the user
     * @return \bool TRUE if it does, FALSE if it doesn't
     */
    public function match(string $pathto) {
        $ROUTE_PARSERS = array(
            'tolower' => function($content) { return strtolower($content); },
            'toupper' => function($content) { return strtoupper($content); },
            'toint' => function($content) { return (int)$content; },
            'tobool' => function($content) { return (bool)$content; }
        );

        $rgxMatches = preg_match($this->pattern, $pathto, $values);

        if (!($rgxMatches) && sizeof($values) <= 0) {
            return false;
        }

        $values = array_slice($values, 1);

        for ($i = 0; $i < sizeof($values); $i++) {
            $key = array_keys($this->parameters)[$i];
            $this->parameters[$key] = $values[$i];
            if (array_key_exists($key, $this->parsers) && $this->parsers[$key] && trim($this->parsers[$key]) != '') {
                $parsers = array_filter(explode(':', $this->parsers[$key]), function($item) { return (bool)$item;});
                ///@debug print_r($parsers);
                foreach ($parsers as $parser) {
                    $parser = $parser == 'toparse' ? $this->customParser : $ROUTE_PARSERS[$parser];
                    $this->parameters[$key] = call_user_func($parser, $this->parameters[$key]);
                }
            }
        }

        return $rgxMatches;
    }

    /**
     * Returns the callback setted by the user to the route
     * represented by this class object.
     * 
     * @return \callable
     */
    public function getCallback() { return $this->callback; }

    /**
     * Returns the route/path parameters defined by the user and parsed
     * by this class.
     * 
     * @return \array
     */
    public function getParsedRouteParameters() {
        if (in_array(null, array_values($this->parameters))) throw new Exception("parsing parameters failed", 1);
        
        return $this->parameters;
    }

    /**
     * Sets a custom parser to the value passed to some route/path parameter.
     * The user may not have access to the `Route` object directly, so,
     * this is used by the `RouteInterface` class.
     * 
     * @param \callable $parser The custom parser to be used during the route parameter parsing.
     */
    public function _addParser(callable $parser) {
        $this->customParser = $parser;
    }
}